### ISSUE TITLE
请教变址寻址中如何确定是否跨页

### ISSUE THREAD

**Issue by nickhelion** [blanboom/bEMU#1]
感谢作者清晰的代码和注释, 对我帮助非常大

不过对代码中,  cpu 变址寻址时发生跨页的条件不太理解

```c
void cpu_addressing_absolute_x() {
    op_address = memory_read_word(cpu.pc) + cpu.x;
    op_value = memory_read_byte(op_address);
    cpu.pc += 2;
    if ((op_address >> 8) != (cpu.pc >> 8)) {
        additional_cycles = 1;
    } else {
        additional_cycles = 0;
    }
}
```
以这段代码为例
文档中的描述
>it uses the 8-bit ALU to first calculate the low byte while it fetches the high byte. If there's a carry out, it goes "oops", applies the carry using the ALU, and repeats the read at the correct address. 

根据我粗浅的理解, 判断地址相加时低 8 位有无发生进位, 应该是判断 `(op_address >> 8) != (memory_read_word(cpu.pc)) >> 8`    

如有理解有误, 望指正

**Comment by blanboom** [comment]
两年前的代码，有不少地方没太大印象了😂 看了一下，你的理解应该是对的，现在的判断有问题。

**Comment by nickhelion** [comment]
感谢回复
